### PR TITLE
Adjust key pressed behaviour when caps lock is on - closes #88

### LINKED ISSUE #88: Keys pressed should have same behavior when caps lock is on
For example, when attempting to delete a state, it currently only accepts the lower case "d". I think allowing the keys pressed events to be triggered by the same key independent of whether caps lock is on or not would present an improvement for the user experience, and allow for less confusion.

### PR DESCRIPTION
**Pull request by YoussefRizkalla**
A simple fix for this issue

### CODE REVIEW

**Review by CSchank — COMMENTED** [review]
Wow - awesome, thank you! I didn't see this before.

**Comment by CSchank** [comment]
One comment is that I would suggest that we do "toLower" on the string (perhaps in a "let") and then we can keep our if expressions on only the lowercase versions. Easier to maintain.

**Comment by YoussefRizkalla** [comment]
Good point; I refactored it according to your suggestion.

**Review by CSchank — COMMENTED** [review]
Great! There are other places in the code we use key presses, including undo and redo, we should probably fix those too. Likely this underscores a need to refactor a bit, since key presses seem to be in different places.

**Comment by YoussefRizkalla** [comment]
I didn't even know that there was a redo functionality 😅. I think that should cover all of the current events.

**Comment by CSchank** [comment]
Aha, a lot of people don't know it does. We should probably put some explicit buttons for some of this stuff. We have proposals to do stuff like this. I'll merge this once I merge things into master properly, as I should have. What you edited is actually an old version before we had saving. It was a bit of a rush at the end there!

**Review by CSchank — APPROVED** [review]
Looks good! Even passed our `elm-format` testing 😃

**Comment by Necried** [comment]
Any reason why this isn't merged yet? Should I do it? @CSchank

**Comment by CSchank** [comment]
@Necried I was waiting on your approval for my PR #90, then I was going to merge this.

**Review by Necried — APPROVED** [review]
@CSchank merge once the other PR is ready. I'm just self-adding my approval here.

**Pull request merged**
